"""Make project_id nullable

Revision ID: df9a47f5d47d
Revises: 7ea7cd2bd57f
Create Date: 2026-05-27 19:16:42.725373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9a47f5d47d'
down_revision: Union[str, Sequence[str], None] = '7ea7cd2bd57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_assets', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('processing_jobs', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_jobs', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audio_assets', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
